### ISSUE TITLE
No file named 'save_style_vector.py'

### ISSUE THREAD

**Issue by kingseeking** [BenjaminJonghyun/SuperStyleNet#2]

**Comment by BenjaminJonghyun** [comment]
Thanks for your patience.
Updating source codes are in progress. So, we will fully update our codes as soon as possible.

**Comment by BenjaminJonghyun** [comment]
We just updated this file. So, I will close this issue.

**Comment by kingseeking** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jonghyun ***@***.***&gt;; 
发送时间: 2021年12月17日(星期五) 下午2:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BenjaminJonghyun/SuperStyleNet] No file named &#39;save_style_vector.py&#39; (Issue #2)





 
We just updated this file. So, I will close this issue.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
